<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<?  if($deleted == true){
    echo "Account $accountId closed successfully";
    ?>
    <br>
    <a href=<?= $linkTo('showAccounts'); ?>>Back</a>
    <? } else {
            echo "Account $accountId closed failed";
    ?>
    <br>
    <a href=<?= $linkTo('showAccounts'); ?>>Back</a>
    <? }?>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>