<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <title>First National Bank</title>
	    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
        <link rel="shortcut icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/static/icons/favicon.ico" type="image/x-icon">
	</head>
	<body>
		<h1>Welcome To First National Bank</h1>
		<br><br><br><br>
		<div class="page-wrap">
<!---------- Header ends --------------->