<?php include "header.phtml" ?>

<h1 align="center">Welcome To First National Bank</h1>

<form align="center" style="padding-top:80px;" method="post">

    <p1>User Name</p1><br>
    <input type="text" name="userName"><br>
    <p1>Password</p1><br>
    <input type="password" name="userPassword"><br><br>
    <input type="submit" value="Login" name="validateLogin">
    <input type="button" value="Sign up">
</form>


