<?php include "header.phtml" ?>

<h1 align="center">Welcome To First National Bank</h1>

<h2 align="center">Please Enter Your Details</h2>

<form align="center" style="padding-top:80px;" method="post" action="">

    <br>
    <p1>User Name</p1><br>
    <input type="text" name="userName"><br><br>
    <p1>Password</p1><br>
    <input type="password" name="userPassword"><br><br>
    <p1>Re-Enter Password</p1><br>
    <input type="password" name="userPassword2"><br><br>
    <input type="submit" value="Sign Up" name="signUp">
    <input type="reset" value="Reset">
</form>


