<?php include "header.phtml" ?>
<!---------- Body starts --------------->

<form style="text-align:center;padding-top:80px;" method="GET">
    <? echo "<h2>Withdrawal from $fromAccountID</h2>
    <p style='color:red;'>$error</p>"?>

    <br>
    <p1>Enter Amount you want to Withdrawal:</p1><br>
    <input type="number" step="0.01" name="wAmount" min="0" required><br><br>
    <input type="submit" value="Submit" name="withdrawal">
</form>

<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>