<!--This page is rendered when user trying to make a transfer.
    User must enter correct amount and correct account id they want to transfer to-->
<?php include "header.phtml" ?>
<!---------- Body starts --------------->

<form style="text-align:center;padding-top:80px;" method="GET", action="">
    <? echo "<h2>Making a Transfer</h2>
    <p style='color:red;'>$error</p>"?>
    <br>
    <p>Account to transfer from:<br>
    <input type="text" name="accountId" value="<? echo $fromAccountID?>" readonly></p>
    <p>Amount to Transfer:<br>
    <input type="number" step="0.01" name="amount" value="<? echo $amount?>" min="0" required></p>
    <p>Account to Transfer to:<br>
    <input type="text" name="toAccount" value="<? echo $toAccount?>" required></p>
    <p><input type="submit" value="Submit" name="submit"></p>
</form>

<br>
<a href="<?= $linkTo('Home'); ?>">Back</a>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>