<!-- This page is rendered when user successfully deposit.Balance after deposit will be showed-->
<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <?echo "Deposit Succesfully"?>
    <br>
    <?echo "<p>Balance for $accountId after deposit : \$$balance</p>"?>
    <a href="<?= $linkTo('showAccounts'); ?>">Back</a>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>