<!-- This page displays all the transactions of one user,
     no matter how many accounts an user has -->
<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h2>The TransHub</h2>
<p>All of your transactions in one place</p>

<table border = "1">
    <tr>
        <th>ID</th>
        <th>Account No.</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Type</th>
    </tr>
    <?php foreach ($transactions as $transaction) { ?>
        <tr>
            <td><?= $transaction->getId() ?></td>
            <td><?= $transaction->getAccountID() ?></td>
            <td><?= $transaction->getTime()->format('Y-m-d H:i:s') ?></td>
            <td><?
                $dollars = $transaction->getAmount() / 100;
                $cents = $transaction->getAmount() % 100;
                echo "\${$dollars}.{$cents}"
                ?></td>
            <td><?= $transaction->getType() ?></td>
        </tr>
    <?php } ?>
</table>

<br>
<a href=<?= $linkTo('Home'); ?>>Back</a>

<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>