<?php include "header.phtml" ?>
<form style="position:fixed;top:0;right:0;"method="get" action="logout">
    <?
    $date = date("i-h-s");
    echo date("l, jS \of F ");
    ?>
<input type="submit" value="Log out" name="logout" style="font-size:16px;">

</form>
<div style="font-size:20px;">

<? $hours = Date('G');
    if($hours >= 6 && $hours < 12){
        echo "<p>Good Morning, $userName</p>";
    } else if($hours >= 12 && $hours < 18){
        echo "<p>Good Afternoon, $userName</p>";
    } else {
        echo "<p>Good Evening, $userName</p>";
    };
?>
</div>  
<div>
    <p1>Your Accounts:</p1><br>

    <table style="border:1px solid black;border-spacing:30px;">
    <tr>
        <th>Account No.</th>
        <th>Name</th>
        <th>Balance</th>
    </tr>

    <? foreach ($accounts as $bankAccount){
        $balance = ($bankAccount->getBalance()) / 100;
        echo "
            <tr>
                <td>{$bankAccount->getID()}</td>
                <td>{$bankAccount->getName()}</td>
                <td>\${$balance}</td>
                <td><a href={$linkTo('accountDelete', ['id' => $bankAccount->getID()])}>delete</a></td>
                <td><a href={$linkTo('deposit', ['id' => $bankAccount->getID()])}>Deposit</a></td>
                <td><a href={$linkTo('TransWithdrawal', ['id' => $bankAccount->getID()])}>Withdrawal</a></td>
                <td><a href={$linkTo('TransTransfer', ['id' => $bankAccount->getID()])}>transfer</a></td>
            </tr>
        ";
    }
    ?>
    </table>

    <br>
    <a href=<?= $linkTo('accountCreate'); ?>>Create Bank Account</a>
    <br><br>
    <a href=<?= $linkTo('TransIndex'); ?>>View All Transactions</a>
</div>

<?php include "footer.phtml" ?>
