<?php include "header.phtml" ?>
<h1 align="center">Welcome to First National Bank</h1>

<form method="get">

<input type="submit" value="Log out" name="logOut">

</form>
<? $hours = Date('G');
    if($hours >= 6 && $hours < 12){
        echo "<p>Good Morning, $userName</p>";
    } else if($hours >= 12 && $hours < 18){
        echo "<p>Good Afternoon, $userName</p>";
    } else {
        echo "<p>Good Evening, $userName</p>";
    };
?>


<?php include "footer.phtml" ?>